config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'projekt' => 'static_pages#projekt'
  get 'news'    => 'static_pages#news'

end

app/controllers/SparqlQueryGenerator.rb
class SparqlQueryGenerator
  
   require 'rubygems'
    require 'sparql/client'
    require 'sparql'	
    require 'linkeddata' 
   
  
  def createQueryList

    @query1 = "
	  PREFIX ontology: <http://dbpedia.org/ontology/>
	  PREFIX dbp: <http://dbpedia.org/property/>
	  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#label>
	  SELECT ?abstract Where{	
		  ?beard rdf:type <http://dbpedia.org/ontology/AnatomicalStructure> .
		  ?beard dct:subject <http://dbpedia.org/resource/Category:Facial_hair> .
		  ?beard dbp:name 'Beard'@en .
		  ?beard ontology:abstract ?abstract .
		  FILTER (Lang(?abstract)='de')
		  }
	  "
    @query2 = "
	  PREFIX ontology: <http://dbpedia.org/ontology/>
	  PREFIX dbp: <http://dbpedia.org/property/>
	  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#label>
	  SELECT ?abstract Where{	
		  ?beard rdf:type <http://dbpedia.org/ontology/AnatomicalStructure> .
		  ?beard dct:subject <http://dbpedia.org/resource/Category:Facial_hair> .
		  ?beard dbp:name 'Beard'@en .
		  ?beard ontology:abstract ?abstract .
		  FILTER (Lang(?abstract)='en')
		  }
    
    "

    
     queries = Array.new(2)
     queries[0] = @query1
     queries[1] = @query2   
     
     queries
  end  
  
  def chooseQuery(queryList)
     
    random = 1 + rand(queryList.length)
    queryList[random-1] 	
  end
  

  def runQueryAgainstDBPedia(query)
      
      client = SPARQL::Client.new("http://dbpedia.org/sparql")
  
      result = client.query(query)
 
      result = result.to_html
      result = result.html_safe
      result

  end




  if __FILE__ == $0
    @mg = SparqlQueryGenerator.new    
    list = @mg.createQueryList
    query = @mg.chooseQuery(list)
    #@mg.runQueryAgainstDBPedia(query)
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
  	render text: "Hello, world!"
  end

   #xml_doc = File.read(Rails.root + 'public/xml/DIP-UBLeipzig-publizierte20150318.xml')
   #obj = Nokogiri::XML(xml_doc)

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	require 'BaseXClient.rb'
  require 'SparqlQuery.rb'

	def about	
	end

	def help	
	end
  
  def home
  		
  end

  def news
  	# create session
  	session = BaseXClient::Session.new("localhost", 1984, "admin", "admin")

    @person=[1]
    @mg = SparqlQuery.new  
    list = @mg.createQueryList
    dbp_query = @mg.chooseQuery(list)
    @result = @mg.runQueryAgainstDBPedia(dbp_query)
    @ratingNode =  @xml_obj.xpath("//obj/Rating")

  	begin
     	# create query instance
  		@input = "//obj[position()<6]/*/a8000/text()"

  		session.execute("open baerte")
  		@query = session.query(@input)
  		# close query instance
  		#print query.close()
  		
  		rescue Exception => e
  			# print exception
 				puts e
 			end

 		# close session
 		# session.close
  		
 		end

  	def contact
  	end
  	def rate
            xml_doc = File.read(Rails.root + 'public/xml/PortraitData.xml')
            @xml_obj = Nokogiri::XML(xml_doc)

=begin
find   object id , clicked rate

    value ++
element xml update
=end
            File.write(xml_doc, @xml_obj.to_xml)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "XML-Projekt"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <%= link_to "XML-Projekt", "https://github.com/cvhf/XML-APP/", :target => "_blank" %>
    by <%= link_to "Team X", about_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Über uns", about_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>
      <li><%= link_to "Neuigkeiten", news_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "baerte app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Galerie",   '#' %></li>
        <li><%= link_to "Hilfe", help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>Das Team</h1>
<ul>
	<li>Christoph van Heteren-Frese</li>
	<li>Bastian Krause</li>
	<li>Daniel Theus</li>
	<li>moslehi85</li>
	<li>Max Ficht</li>
</ul>

app/views/static_pages/contact.html.erb
<h1>Kontakt</h1>

app/views/static_pages/help.html.erb
<h1>Um was geht es hier?</h1>
<h4>Diese Projekt ist im Rahmen des Moduls <i>XML-Technologien</i> an der Freien Universität entstanden.</h4>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>XML-Projekt <i>"Bärte"</i></h1>

  <h2>
    Hier entsteht die Projektseite der
     <a href="http://www.mi.fu-berlin.de/inf/groups/hcc/teaching/Sommersemester-2016/Vorlesung_XML.html">XML-Technologien</a>
    Beispielanwendung.
  </h2>
  <p>
  	<%= link_to image_tag("16854286157_2734093abc_z.jpg", alt: "Mann mit Bart", size: "290x320"),'#' %>
  </p>
  <p><%= link_to "Los gehts!", news_path , class: "btn btn-lg btn-primary" %></p>
</div>

app/views/static_pages/news.html.erb
<h1>Bärte-Quiz</h1>
	<!--
	<ul>
		<% while @query.more do %>
     		<li><%= @query.next %></li>
     	<% end%> 
	</ul>
	-->

	<% @person.each do |p| %>
	<div class="row">
		<div class="col-sm-6">
			<div class="panel panel-default">
				<div class="panel-heading">Bild</div>
				<div class="panel-body">
					<%= link_to image_tag("16854286157_2734093abc_z.jpg", alt: "Mann mit Bart", size: "290x320"),'#' %>
				</div>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="panel panel-default">
				<div class="panel-heading">Infos</div>
				<div class="panel-body">
					Hier kommen die Daten aus unserer XML-Datei rein. <%= debug @result %>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="panel panel-default">
				<div class="panel-heading">Zusätzliche Informationen:</div>
				<div class="panel-body">
					<%= @result.html_safe %>
				</div>
			</div>
		</div>
	</div>
	<% end %>
	<!--
	<div id="content">Dynamic Content goes here</div>
    <div id="page-selection">Pagination goes here</div>
    <script>
        // init bootpag
        $('#page-selection').bootpag({
            total: 5
        }).on("page", function(event, /* page number here */ num){
             $("#content").html("Insert content"); // some ajax content loading...
        });
    </script>
	-->
	<ul class="pager">
		<li><a href="#">Previous</a></li>
		<li><a href="#">Next</a></li>
	</ul>

app/views/static_pages/projekt.html.erb
<div class="center jumbotron">
  <h1>XML-Projekt <i>"Bärte"</i></h1>

  <h2>
    Hier entsteht die Projektseite der
     <a href="http://www.mi.fu-berlin.de/inf/groups/hcc/teaching/Sommersemester-2016/Vorlesung_XML.html">XML-Technologien</a>
    Beispielanwendung.
  </h2>
  <div>
  	<%= link_to image_tag("16854286157_2734093abc_z.jpg", alt: "Mann mit Bart", size: "290x320"),'#' %>
  </div>
  <!--<%= link_to "Die Projektidee...", '#', class: "btn btn-lg btn-primary" %>-->
</div>